---
- name: Exercise 3
  hosts: cisco1, cisco2
  gather_facts: False
  tasks:

    - name: Gather "show lldp neighbors"
      cisco.ios.ios_command:
        commands:
          - show lldp neighbors
      register: output

    - name: Gather relevant lines from Ansible output
      ansible.builtin.set_fact:
        lldp_output: "{{ output['stdout_lines'][0] }}"

    - name: Look for "twb-sf-hpsw1" in output of lldp neighbors
      ansible.builtin.set_fact:
        lldp_entry: "{{ item }}"
      loop: "{{ lldp_output }}"
      when: "'twb-sf-hpsw1' in item"

    - name: Set facts for remote device, local interface and remote interface
      ansible.builtin.set_fact:
        remote_device: "{{ lldp_entry.split()[0] }}"
        local_intf: "{{ lldp_entry.split()[1] }}"
        remote_intf: "{{ lldp_entry.split()[-1] }}"

    - ansible.builtin.debug:
        msg:
          - "Remote device: {{ remote_device }}"
          - "Local interface: {{ local_intf }}"
          - "Remote interface: {{ remote_intf }}"
