---
- name: Exercise 3
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Set Eth1/4 interface IP address
      cisco.nxos.nxos_l3_interfaces:
        config:
          - name: "{{ intf_name }}"
            ipv4:
              - address: "{{ intf_ip_addr }}/{{ intf_netmask }}"
        state: merged

    - name: Test connectivty to other NXOS devices
      ansible.netcommon.net_ping:
        dest: "{{ nxos_neighbor }}"
      register: ping_stats
      tags: pingtest

    - name: Verify that ping was successful
      assert:
        that:
          - ping_stats.packets_rx >= 4
      tags: pingtest
