---
- name: Exercise 5
  hosts: juniper
  gather_facts: False
  tasks:

    - name: show interfaces terse
      junipernetworks.junos.junos_command:
        commands: show interfaces terse
      register: interfaces

    - name: display output
      ansible.builtin.debug:
        var: interfaces

    - name: display fxp0.0 interface
      ansible.builtin.debug:
        var: interfaces['stdout_lines'][0][21]
